language: ruby
sudo: false
rvm:
  - 2.2
before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - gem update bundler
script:
  - bundle exec jekyll build --drafts
#  - bundle exec htmlproof ./_site
notifications:
  email:
    - ogataken@gmail.com
branches:
  only:
    - gh-pages
